flowchart TB
    User --> PortForward[Virtual Box Port Forwarding 3000,9090,5050] <-.-> APP & PROM & GRAF
    subgraph LVM["Local VM  (VirtualBox / Ubuntu)"]
        direction TB
        APP[".NET Web API:5000"]
        NE["Node Exporter:9100"]
        PROM["Prometheus:9090"]
        GRAF["Grafana:3000"]
        SCRIPT["Python push script
        prom_to_cw.py · systemd"]

        NE -->|"scrape every 15s"| PROM
        APP -->|"expose /metrics"| PROM
        PROM -->|"data source"| GRAF
        PROM -->|"query metrics"| SCRIPT
    end

    subgraph AWS["AWS Cloud"]
        direction TB

        subgraph CW["CloudWatch"]
            CWMET["Custom metrics
            Ubuntu/Prometheus-Local-VM"]
            CWALM["Alarms CPU > 75% | MEM > 75%"]
            CWDASH["Dashboard"]
            CWMET --> CWALM
            CWMET --> CWDASH
        end

        subgraph ASG["Auto Scaling Group- auto-sg"]
            POLICY["Scaling Policy +1 instances on alarm"]
            LT["Launch Template t3.micro - Free Tier · Amazon Linux AMI"]
            EC2A["EC2 Instance 1 t3.micro"]
            EC2B["EC2 Instance 2 t3.micro"]
            EC2N["EC2 Instance up to 3 max"]
            POLICY --> LT
            LT --> EC2A
            LT --> EC2B
            LT --> EC2N
        end

        CW -->|"alarm triggers set desired capacity"| POLICY
    end

    SCRIPT -->|"PutMetricData boto3 · every 10s"| CWMET